name: Build and Push Docker Image Horizon # Nome do workflow

on:
  push:
    branches:
      - main # Branch que ativará o workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositório e da branch atual
      - name: Checkout repository
        uses: actions/checkout@v3

      # Build da imagem Docker
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/node-horizon:latest .

      # Login no Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Push da imagem para o Docker Hub
      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/node-horizon:latest
